# Generated by Django 3.1 on 2020-08-30 15:41

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200829_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='attachment_img',
            field=models.ImageField(upload_to=posts.models.PostAttachment.get_upload_path),
        ),
    ]
